/** Orbiting Archive design reminder: the hub remains a constellation map, now adding recruiter-friendly filtering, experience context, and Sparsh Mishra’s direct contact actions. */
import { motion } from "framer-motion";
import { ArrowDownRight, ArrowUpRight, Command, Download, ExternalLink, Sparkles } from "lucide-react";
import { useMemo, useState } from "react";
import { Link } from "wouter";
import { portfolios } from "@/data/portfolios";
import { hubFilters, sparshProfile, worldFilterTags } from "@/data/profile";
import { masterLibraryZip } from "@/data/designLibrary";
import { OrbitMark } from "@/components/brand/OrbitMark";
import { ContactForm } from "@/components/shared/ContactForm";
import { DesignPreviewModal } from "@/components/library/DesignPreviewModal";
import { BeginnerSetupGuide } from "@/components/library/BeginnerSetupGuide";

const visibleImages = ["kinetic", "architect", "void"];
export function ConstellationHub() {
  const [filter, setFilter] = useState<(typeof hubFilters)[number]>("ALL");
  const filteredPortfolios = useMemo(() => portfolios.filter((portfolio) => { const tags = worldFilterTags[portfolio.slug]; return filter === "ALL" || tags.skills.includes(filter) || tags.types.includes(filter); }), [filter]);
  return <div className="constellation-page" data-cursor-color="#d9ff4a"><div className="constellation-noise" aria-hidden="true" />
    <header className="hub-nav"><OrbitMark /><div className="hub-nav__right"><span className="hub-nav__status"><i /> {sparshProfile.availability.toUpperCase()}</span><a href={masterLibraryZip} className="hub-nav__library" download data-cursor-label="LIBRARY"><Download size={14}/> RETRIEVE LIBRARY</a><a href="#worlds" className="hub-nav__control" data-cursor-label="EXPLORE">EXPLORE <ArrowDownRight size={16} /></a></div></header>
    <main><section className="hub-hero"><div className="hub-hero__image" aria-hidden="true" /><div className="hub-hero__rays" aria-hidden="true" />
      <motion.div className="hub-hero__intro" initial={{ opacity: 0, y: 24 }} animate={{ opacity: 1, y: 0 }} transition={{ duration: 0.65, ease: [0.23, 1, 0.32, 1] }}><p className="signal-label"><Sparkles size={14} /> SPARSH MISHRA / B.TECH STUDENT / PERSONAL BRAND UNIVERSE</p><h1>Curious by<br />nature. <em>Built</em><br />to ship.</h1></motion.div>
      <motion.div className="hub-hero__side" initial={{ opacity: 0 }} animate={{ opacity: 1 }} transition={{ delay: 0.45, duration: 0.5 }}><span className="hub-hero__side-line" /><p>{sparshProfile.audience}</p></motion.div>
      <div className="hub-hero__orbital-stamp" aria-hidden="true"><span>SPARSH<br />MISHRA<br />2026</span><Command size={23} /></div><p className="hub-hero__signature" aria-hidden="true">SPARSH MISHRA /<br />PORTFOLIO CONSTELLATION</p><div className="hub-scrollcue"><span>SCROLL TO EXPLORE</span><div /></div></section>
      <section className="candidate-brief"><div><p className="signal-label candidate-brief__eyebrow">CANDIDATE SIGNAL / OPEN FOR OPPORTUNITY</p><h2>Design, code,<br /><em>and a point of view.</em></h2></div><div className="candidate-brief__right"><p className="candidate-brief__quote">“{sparshProfile.quote}”</p><div className="candidate-brief__meta"><div><span>ROLE</span><p>{sparshProfile.role}</p></div><div><span>LOCATION</span><p>{sparshProfile.location}</p></div><div><span>CONTACT</span><p>{sparshProfile.phone}</p></div><div><span>FOCUS</span><p>Product, identity, frontend</p></div></div></div></section>
      <section id="worlds" className="worlds-section"><div className="worlds-section__heading"><p className="signal-label">FIELD INDEX / {filteredPortfolios.length.toString().padStart(2, "0")} OF 08 PORTFOLIO WORLDS</p><h2>Work with<br /><span>range and intent.</span></h2><p className="worlds-section__desc">Filter the portfolio by skills and project types, or enter a world to see the thinking, process, and visual system behind each project.</p><div className="worlds-section__coordinates"><span>STUDENT BUILDER / 2026</span><span>AXIS: {filter}</span><span>MODE: EXPLORE</span></div><div className="filter-panel" aria-label="Filter portfolio worlds"><span className="filter-panel__label">FILTER SIGNALS</span><span className="filter-panel__count">{filteredPortfolios.length} MATCHING</span>{hubFilters.map((item) => <button type="button" key={item} className="filter-chip" aria-pressed={filter === item} onClick={() => setFilter(item)} data-cursor-label="FILTER">{item}</button>)}</div></div><div className="worlds-section__constellation-seal"><img src="/manus-storage/eclipse-mark_52f7be4f.png" alt="" /><span>THE ECLIPSE MARK IS THE CREATOR PULSE</span></div><div className="orbit-diagram" aria-hidden="true"><span className="orbit-diagram__one" /><span className="orbit-diagram__two" /><span className="orbit-diagram__core" /></div>
        <div className="worlds-list"><div className="worlds-list__legend"><span>MAP VIEW / {filter}</span><span>SELECT A NODE TO OPEN ITS CASES</span></div><svg className="worlds-map" viewBox="0 0 1200 2200" preserveAspectRatio="none"><path d="M175,185 C555,245 910,125 990,480 S750,720 410,800 S185,1180 700,1260 S1060,1520 720,1650 S360,1950 795,2090"/><path d="M175,185 C305,340 950,310 990,480 M410,800 C600,600 830,920 700,1260 M700,1260 C420,1470 1030,1510 720,1650"/><circle cx="175" cy="185" r="12"/><circle cx="990" cy="480" r="12"/><circle cx="410" cy="800" r="12"/><circle cx="700" cy="1260" r="12"/><circle cx="1020" cy="1480" r="12"/><circle cx="720" cy="1650" r="12"/><circle cx="350" cy="1900" r="12"/><circle cx="795" cy="2090" r="12"/></svg>{filteredPortfolios.map((portfolio, index) => { const tags = worldFilterTags[portfolio.slug]; return <motion.div key={portfolio.id} className={`world-card world-card--${portfolio.slug}`} initial={{ opacity: 0, y: 32 }} animate={{ opacity: 1, y: 0 }} transition={{ duration: 0.42, delay: (index % 3) * 0.05, ease: [0.23, 1, 0.32, 1] }}><Link href={`/portfolios/${portfolio.slug}`} className="world-card__link" data-cursor-label="OPEN" data-cursor-color={portfolio.accent}><div className="world-card__media" style={{ "--world-accent": portfolio.accent } as React.CSSProperties}>{visibleImages.includes(portfolio.slug) ? <img src={portfolio.image} alt="" /> : <WorldGraphic mode={portfolio.slug} />}<div className="world-card__media-grid" /><span className="world-card__number">{portfolio.number}</span><span className="world-card__coordinate">{portfolio.coordinate}</span><span className="world-card__open">OPEN <ArrowUpRight size={16} /></span></div><div className="world-card__copy"><div><p className="world-card__discipline">{portfolio.discipline}</p><h3>{portfolio.title}</h3></div><p className="world-card__caption">{portfolio.caption}</p></div><p className="world-card__audience">{tags.audience}</p></Link><DesignPreviewModal world={portfolio}/></motion.div>; })}</div></section>
      <BeginnerSetupGuide/><section className="candidate-experience"><div className="candidate-experience__head"><div><p className="signal-label">EXPERIENCE / EDUCATION / PRACTICE</p><h2>Signals from<br /><em>the real work.</em></h2></div><p className="worlds-section__desc">A B.Tech student portfolio built to help recruiters and founders quickly see what Sparsh is exploring, making, and ready to contribute.</p></div><ol className="experience-list">{sparshProfile.experiences.map((experience) => <li key={experience.period}><span className="experience-list__period">{experience.period}</span><div><h3>{experience.title}</h3><p className="experience-list__place">{experience.place}</p></div><p className="experience-list__detail">{experience.detail}</p></li>)}</ol></section>
      <section className="hub-manifesto hub-manifesto--contact"><p className="signal-label">CONTACT SIGNAL / RECRUITERS · FOUNDERS · COLLABORATORS</p><p className="hub-manifesto__copy">Let’s make the next <span>useful, memorable thing.</span></p><div className="contact-grid"><a className="contact-action contact-action--primary" href="/manus-storage/Sparsh-Mishra-Resume-Demo_9feec912.pdf" download data-cursor-label="DOWNLOAD"><span>DOWNLOAD RÉSUMÉ <Download size={19} /></span><span className="contact-action__small">ATS-FRIENDLY B.TECH STUDENT RÉSUMÉ / DEMO</span></a><a className="contact-action" href={`mailto:${sparshProfile.email}`} data-cursor-label="EMAIL"><span>START A CONVERSATION <ArrowUpRight size={19} /></span><span className="contact-action__small">{sparshProfile.email} · {sparshProfile.phone}</span></a></div><ContactForm/><div className="contact-socials">{sparshProfile.socials.map((social) => <a href={social.href} target="_blank" rel="noreferrer" key={social.label} title={social.note} data-cursor-label="VISIT">{social.label} <ExternalLink size={12} /></a>)}</div><p className="contact-student-note">{sparshProfile.availability} Contact details and social URLs are clearly marked demo placeholders—replace them with Sparsh Mishra’s verified details before applications.</p></section></main>
    <footer className="hub-footer"><span>© 2026 SPARSH MISHRA / PORTFOLIO CONSTELLATION</span><span>DESIGN + CODE + CURIOSITY</span><span>BENGALURU / REMOTE</span></footer></div>;
}
function WorldGraphic({ mode }: { mode: string }) { return <div className={`world-graphic world-graphic--${mode}`} aria-hidden="true"><span /><span /><span /><b /></div>; }
