/** Orbiting Archive design reminder: discovery is spatial and asymmetric, guided by an eight-world constellation rather than a default card grid. */
import { motion } from "framer-motion";
import { ArrowDownRight, ArrowUpRight, Command, Sparkles } from "lucide-react";
import { Link } from "wouter";
import { portfolios } from "@/data/portfolios";
import { OrbitMark } from "@/components/brand/OrbitMark";

const visibleImages = ["kinetic", "architect", "void"];
export function ConstellationHub() {
  return <div className="constellation-page"><div className="constellation-noise" aria-hidden="true" />
    <header className="hub-nav"><OrbitMark /><div className="hub-nav__right"><span className="hub-nav__status"><i /> AVAILABLE FOR SELECTED WORK</span><a href="#worlds" className="hub-nav__control">EXPLORE <ArrowDownRight size={16} /></a></div></header>
    <main><section className="hub-hero"><div className="hub-hero__image" aria-hidden="true" /><div className="hub-hero__rays" aria-hidden="true" />
      <motion.div className="hub-hero__intro" initial={{ opacity: 0, y: 24 }} animate={{ opacity: 1, y: 0 }} transition={{ duration: 0.65, ease: [0.23, 1, 0.32, 1] }}><p className="signal-label"><Sparkles size={14} /> PERSONAL BRAND UNIVERSE / 2026</p><h1>Eight signals.<br /><em>One</em> creative<br />frequency.</h1></motion.div>
      <motion.div className="hub-hero__side" initial={{ opacity: 0 }} animate={{ opacity: 1 }} transition={{ delay: 0.45, duration: 0.5 }}><span className="hub-hero__side-line" /><p>A set of eight fully formed portfolio identities for the maker who contains more than one practice.</p></motion.div>
      <div className="hub-hero__orbital-stamp" aria-hidden="true"><span>OPEN<br />THE<br />FIELD</span><Command size={23} /></div><p className="hub-hero__signature" aria-hidden="true">PORTFOLIO /<br />CONSTELLATION</p><div className="hub-scrollcue"><span>SCROLL TO NAVIGATE</span><div /></div></section>
      <section id="worlds" className="worlds-section"><div className="worlds-section__heading"><p className="signal-label">FIELD INDEX / 08 CREATIVE WORLDS</p><h2>Choose a<br /><span>point of view.</span></h2><p className="worlds-section__desc">Each route is a deliberately distinct portfolio system. The paths show how eight practices orbit one shared creative signal.</p><div className="worlds-section__coordinates"><span>FIELD: 24.08 / LIVE</span><span>AXIS: 08 / 08</span><span>MODE: EXPLORE</span></div></div><div className="orbit-diagram" aria-hidden="true"><span className="orbit-diagram__one" /><span className="orbit-diagram__two" /><span className="orbit-diagram__core" /></div>
        <div className="worlds-list"><svg className="worlds-map" viewBox="0 0 1200 2200" preserveAspectRatio="none" aria-hidden="true"><path d="M175,185 C555,245 910,125 990,480 S750,720 410,800 S185,1180 700,1260 S1060,1520 720,1650 S360,1950 795,2090"/><path d="M175,185 C305,340 950,310 990,480 M410,800 C600,600 830,920 700,1260 M700,1260 C420,1470 1030,1510 720,1650"/><circle cx="175" cy="185" r="12"/><circle cx="990" cy="480" r="12"/><circle cx="410" cy="800" r="12"/><circle cx="700" cy="1260" r="12"/><circle cx="1020" cy="1480" r="12"/><circle cx="720" cy="1650" r="12"/><circle cx="350" cy="1900" r="12"/><circle cx="795" cy="2090" r="12"/></svg>{portfolios.map((portfolio, index) => <motion.div key={portfolio.id} className={`world-card world-card--${portfolio.slug}`} initial={{ opacity: 0, y: 32 }} whileInView={{ opacity: 1, y: 0 }} viewport={{ once: true, amount: 0.15 }} transition={{ duration: 0.52, delay: (index % 3) * 0.07, ease: [0.23, 1, 0.32, 1] }}><Link href={`/portfolios/${portfolio.slug}`} className="world-card__link"><div className="world-card__media" style={{ "--world-accent": portfolio.accent } as React.CSSProperties}>{visibleImages.includes(portfolio.slug) ? <img src={portfolio.image} alt="" /> : <WorldGraphic mode={portfolio.slug} />}<div className="world-card__media-grid" /><span className="world-card__number">{portfolio.number}</span><span className="world-card__coordinate">{portfolio.coordinate}</span><span className="world-card__open">OPEN <ArrowUpRight size={16} /></span></div><div className="world-card__copy"><div><p className="world-card__discipline">{portfolio.discipline}</p><h3>{portfolio.title}</h3></div><p className="world-card__caption">{portfolio.caption}</p></div></Link></motion.div>)}</div></section>
      <section className="hub-manifesto"><p className="signal-label">CREATIVE POSITION / UNLOCKED</p><p className="hub-manifesto__copy">I design experiences with <span>instinct</span>, then make them work with intent.</p><a className="hub-contact" href="mailto:signal@yourdomain.com">DROP A SIGNAL <ArrowUpRight size={18} /></a><p className="hub-contact__note">SIGNAL@YOURDOMAIN.COM — REPLACE WITH YOUR WORK EMAIL</p></section></main>
    <footer className="hub-footer"><span>© 2026 PORTFOLIO CONSTELLATION</span><span>BUILD STRANGE THINGS WITH CARE</span><span>GLOBAL / REMOTE</span></footer></div>;
}
function WorldGraphic({ mode }: { mode: string }) { return <div className={`world-graphic world-graphic--${mode}`} aria-hidden="true"><span /><span /><span /><b /></div>; }
