/** Orbiting Archive design reminder: one persistent return path and signal language gives every radically different world a shared origin. */
import { motion } from "framer-motion";
import { ArrowDownRight, ArrowLeft, ArrowUpRight, Download, Plus } from "lucide-react";
import { Link } from "wouter";
import type { PortfolioWorld } from "@/data/portfolios";
import { toSlug } from "@/data/caseStudies";
import { designGuides, designSourceZips } from "@/data/designLibrary";
import { OrbitMark } from "@/components/brand/OrbitMark";
import { TiltLink } from "@/components/shared/TiltLink";

export function WorldShell({ world }: { world: PortfolioWorld }) {
  const order = ["kinetic", "architect", "void", "artifact", "mono", "neon", "editorial", "chrome"];
  const nextSlug = order[(order.indexOf(world.slug) + 1) % order.length];
  const guide = designGuides[world.slug];
  return <div className={`portfolio-world portfolio-world--${world.mode} ${world.dark ? "is-dark" : ""}`} style={{ "--accent": world.accent } as React.CSSProperties} data-cursor-color={world.accent}>
    <header className="world-nav"><Link href="/" className="world-nav__back"><ArrowLeft size={16} /> ALL WORLDS</Link><OrbitMark compact invert={world.dark} /><span className="world-nav__coordinates">{world.coordinate}</span></header>
    <main><section className="world-hero"><motion.div className="world-hero__copy" initial={{ opacity: 0, y: 30 }} animate={{ opacity: 1, y: 0 }} transition={{ duration: 0.6, ease: [0.23, 1, 0.32, 1] }}><p className="signal-label">SPARSH MISHRA / SIGNAL {world.number} / {world.tags.join(" · ")}</p><h1>{world.title}</h1><p className="world-hero__caption">{world.caption}</p><p className="world-hero__discipline">{world.discipline}</p></motion.div><div className={`world-hero__art world-hero__art--${world.mode}`}>{world.image ? <img src={world.image} alt="" /> : <WorldHeroGraphic mode={world.mode} />}<span className="world-hero__mode">{world.mode.toUpperCase()} / ACTIVE</span></div><div className="world-hero__edge"><span>SPARSH MISHRA<br />CONSTELLATION</span><ArrowDownRight size={20} /></div></section>
      <section className="design-fit"><div className="design-fit__head"><div><p className="signal-label">DESIGN FIT / {world.number}</p><h2>{guide.label}<br/><em>for your work.</em></h2></div><p className="design-fit__lede">{guide.fit}</p></div><div className="design-fit__grid"><div><span>BEST FOR</span><p>{guide.bestFor}</p></div><div><span>SIGNATURE STRENGTH</span><p>{guide.strength}</p></div><div><span>DIFFICULTY</span><p>{guide.difficulty} to customize</p></div><div><span>START HERE</span><p>{guide.customStart}</p></div></div><div className="design-fit__tags">{guide.personality.map((tag) => <span key={tag}>{tag}</span>)}</div><div className="design-fit__note"><p><strong>CHOOSE THIS WHEN</strong><br/>{guide.useWhen}</p><p><strong>NOT THE BEST FIT WHEN</strong><br/>{guide.avoidWhen}</p></div><a className="design-fit__download" href={designSourceZips[world.slug]} download data-cursor-label="SOURCE" data-cursor-color="#d9ff4a">DOWNLOAD {guide.label.toUpperCase()} SOURCE <Download size={17}/><span>STARTER FOLDER + README</span></a></section>
      <section className={`world-cases world-cases--${world.mode}`}><div className="world-cases__head"><p className="signal-label">SELECTED CASE STUDIES</p><span>03</span></div><div className="case-list">{world.cases.map((caseItem, i) => <TiltLink href={`/case-studies/${world.slug}/${toSlug(caseItem.title)}`} className="case-row" color={world.accent} key={caseItem.title}><span className="case-row__index">0{i + 1}</span><div><h2>{caseItem.title}</h2><p>{caseItem.type}</p></div><span className="case-row__year">{caseItem.year}</span><span className="case-row__button" aria-label={`Read ${caseItem.title} case study`}><Plus size={20} /></span></TiltLink>)}</div></section>
      <section className="world-statement"><p className="signal-label">SPARSH MISHRA / PRACTICE NOTE / 00{world.number}</p><p>{world.description}</p></section><Link href={`/portfolios/${nextSlug}`} className="next-world">NEXT SIGNAL <span>{world.number === "08" ? "01" : String(Number(world.number) + 1).padStart(2, "0")}</span><ArrowUpRight size={22} /></Link></main>
    <footer className="world-footer"><span>SPARSH MISHRA / PORTFOLIO CONSTELLATION</span><a href="mailto:sparsh@constellation.studio">SPARSH@CONSTELLATION.STUDIO</a><span>{world.discipline.toUpperCase()}</span></footer></div>;
}
function WorldHeroGraphic({ mode }: { mode: string }) { return <div className={`hero-graphic hero-graphic--${mode}`} aria-hidden="true"><i /><i /><i /><b /></div>; }
